### PR TITLE
Improved PR #235

### PR DESCRIPTION
**Pull request by BetimBeja**
Improved user experience and error handling, and fixed the `Live Update` bug.

I don't know if I could have pushed the commit to the old PR #235 since you already merged that into branch Pull235, so I am creating a new PR.

Best regards,
Betim.

### CODE REVIEW

**Comment by rappen** [comment]
Sorry... just updated the branch with fixes for LiveUpdate, failsafe parsing of query, and correct method of updating query from the parsed code.
I'd recommend re-forking this branch and applying the fixes you want to that code.
(I'm no git wiz)

**Comment by rappen** [comment]
I'd also recommend looking at my changes 😊

**Comment by BetimBeja** [comment]
@rappen finally I made it. I did force push the changes because I don't like all the merge commits 😊
Now I can proudly say "It works on my computer" 😊

**Comment by rappen** [comment]
And now I finally merged it to master!
@BetimBeja  I am still a bit unsure about merges, could you please verify the current code in master branch? Thanks!

**Comment by BetimBeja** [comment]
Hello @rappen,
I think you only merged PR #235 , and did not merge this PR.  I made Improvements to the user experience in this commit by showing the progress indicator but it is not in the master branch. 😢

**Pull request closed without merging**
